#This workflow will be used for building and testing the code
name: build and test

on:
    push:
        branches: [master]

jobs:
    build:
        name: Build and test
        runs-on: ubuntu-latest
        
        steps:
        #Workflow needs a copy of code and must use checkout action before building and testing code
     
        - uses: actions/checkout@v2
        
        #HTML5 Validator 
       
        - uses: Cyb3r-Jak3/html5validator-action@v0.4
          with:
            # Path of the files to test
            root: .
            format: text
        
        #Use Upload Build Artifact Actions to auto generate log file after running the HTML5 Validator
        - run: mkdir -p log_builds
        
        - run: echo hello > log_builds/logs.txt
        
        - uses: actions/upload-artifact@v2
          with:
            name: build-artifact
            path: log_builds/logs.txt
