#This workflow will be used for building and testing the code
name: build and test

on:
    push:
        branches: [master]

jobs:
    copy:
        name: Copy code
        runs-on: ubuntu-latest
        
        steps:
        #Workflow needs a copy of code and must use checkout action before building and testing code
     
        - uses: actions/checkout@v1
        
    build:
        name: Build and test
        
        needs: copy
        runs-on: ubuntu-latest
        #HTML5 Validator
        
        steps:
       
        - uses: Cyb3r-Jak3/html5validator-action@v0.4
          with:
            # Path of the files to test
            root: ./index.html
            format: text
        
        #Use Upload Build Artifact Actions to auto generate log file after running the HTML5 Validator
        
        - uses: actions/upload-artifact@v1
          with:
            name: log
            path: log.log
