#This workflow will be used for building and testing the code
name: build and test

on:
    push:
        branches: [master]

jobs:
    build:
        name: Build and test
        runs-on: ubuntu-latest
        
        steps:
        #Workflow needs a copy of code and must use checkout action before building and testing code
        - name: Checkout code
          uses: actions/checkout@v2
        
        #HTML5 Validator 
        - name: HTML5 Validator
          uses: Cyb3r-Jak3/html5validator-action@v0.4
          with:
            # Path of the files to test
            root: # default is .
            # Extra arguments to test with
            extra: # optional
            # Format for logging output. Valid values: gnu,xml,json,text
            format: # optional
            # Logging Level. Valid values: DEBUG, INFO, WARNING. Default: WARNING
            log_level: # optional, default is WARNING
            # Checks css as well
            css: # optional
            # Flag that increase verbose output only used for troubleshooting the action.
            action_debug: # optional